exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('personagem').del()
    .then(() =>
      // Inserts seed entries
      knex('personagem').insert([
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Stew',
          age: 1,
          condition: 'vivo',
          image: 'http://localhost:3000/2.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Christopher Cross Griffin',
          age: 14,
          condition: 'vivo',
          image: 'http://localhost:3000/3.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Justin Peter Griffin',
          age: 58,
          condition: 'vivo',
          image: 'http://localhost:3000/4.jpg',
          nationality: 'Estadunidense (nascido no México)',
          genre: 'Masculino',
        },
        {
          name: 'Jasper',
          age: -1,
          condition: 'vivo',
          image: 'http://localhost:3000/5.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        }, {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
        {
          name: 'Brian Griffin (sobrenome dado por cortesia)',
          age: 56,
          condition: 'vivo',
          image: 'http://localhost:3000/1.jpg',
          nationality: 'Estadunidense',
          genre: 'Masculino',
        },
      ]));
};
