exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('personagem').del()
    .then(() =>
      // Inserts seed entries
      knex('personagem').insert([
        {
          name: 'Abuela Alvarez',
          age: 'Unknow',
          condition: 'alive',
          image: 'http://localhost:3001/1.png',
          occupation: 'Hispanic',
          genre: 'Female',
          information: 'Abuela Alvarez is the grandmother of Gina Alvarez. She appeared in "The Shame Wizard".',
        },
        {
          name: 'Aiden',
          age: '13',
          condition: 'alive',
          image: 'http://localhost:3001/2.png',
          occupation: 'Student',
          genre: 'Male',
          information: 'Aiden first appeared in My Furry Valentine, when he and Matthew happened to meet at a pharmacy and Maurys gaydar was going off the charts, indicating that Aiden is gay.',
        },
        {
          name: 'Ali',
          age: '12-13',
          condition: 'alive',
          image: 'http://localhost:3001/3.png',
          occupation: 'Student',
          genre: 'Female',
          information: 'Ali is a young Asian girl and the new student at Bridgeton Middle School who was transferred from Our Lady in the Water and she quickly became the "it girl" at school after admitting that she is pansexual.',
        },
        {
          name: 'Allergy Kid',
          age: 'Unknow',
          condition: 'Alive',
          image: 'http://localhost:3001/4.1.png',
          occupation: 'Student',
          genre: 'Male',
          information: 'The Allergy Kid is an unnamed student at Bridgeton Middle School who has a deadly peanut allergy. He mostly serves as a background character but had a speaking part in "The ASSes".',
        },
        {
          name: 'Ambition Gremlin',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/4.2.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'The Ambition Gremlin represents the ambition of the humans. He believes more in success than feeling good. He has green skin, big ears, slicked-back dark green hair and violet eyes.',
        },
        {
          name: 'Andrew 3001',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/4.3.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Andrew 3001 is a robot version of Andrew Glouberman from the future. He appeared in "Drug Buddies".',
        },
        {
          name: 'Andrew Glouberman',
          age: '12',
          condition: 'alive',
          image: 'http://localhost:3001/4.png',
          occupation: 'Student at Bridgeton Middle School',
          genre: 'Male',
          information: 'Andrew Glouberman is the secondary main character of Big Mouth. He is the 12-year-old best friend of Nick Birch, who goes to Bridgeton Middle School and lives in a suburban house in Westchester, New York. As if being a socially awkward dork wasnt enough, puberty has hit Andrew like an oncoming train, turning him into a greasy, hairy mid-pubescent mess, who gets driven to madness by his hormone monster, Maury, who constantly urges him to masturbate, even at the worst possible times. He is voiced by John Mulaney.',
        },
        {
          name: 'Andy Garcia',
          age: 'Unknow',
          condition: 'alive',
          image: 'http://localhost:3001/5.png',
          occupation: 'Actor',
          genre: 'Male',
          information: 'Andrés Arturo "Andy" García Menéndez is a famous actor. He appeared in Missys imagination sequence in "The ASSes".',
        },
        {
          name: 'Antoni Porowski',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/6.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Atoni Porowski is the main character of Queer Eye. He appeared in the Big Mouth episode, "Disclosure the Movie: The Musical!".',
        },
        {
          name: 'Antonin Scalia',
          age: 'Unknow',
          condition: 'dead',
          image: 'http://localhost:3001/7.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Antonin Gregory Scalia was a supreme court lawyer. He was portrayed as a homosexual ghost in Big Mouth.',
        },
        {
          name: 'Anxiety Armadillo',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/8.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'Anxiety Armadillo represents the anxiety in humans. The character is shy and doesnt speak in congress. He has yellow and orange skin.',
        },
        {
          name: 'Aretha Franklin',
          age: 'Unknow',
          condition: 'dead',
          image: 'http://localhost:3001/9.png',
          occupation: 'Unknow',
          genre: 'Female',
          information: 'Aretha Louise Franklin was a famous singer. She appeared in "Duke".',
        },
        {
          name: 'Bad Mitten',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/10.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'The Bad Mitten is an evil sentient mitten that appeared in "The Shame Wizard".',
        },
        {
          name: 'Barbara Glouberman',
          age: '56',
          condition: 'Alive',
          image: 'http://localhost:3001/11.png',
          occupation: 'Unknow',
          genre: 'Female',
          information: 'Barbara Glouberman is a supporting character on the Netflix adult animated series, Big Mouth. She is the mother of Andrew Glouberman and wife of Marty Glouberman. She is portrayed by Paula Pell.',
        },
        {
          name: 'Bethany',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/12.png',
          occupation: 'Unknow',
          genre: 'Female',
          information: 'Bethany is a girl from a porn video on the internet. She appeared in "How To Have An Orgasm".',
        },
        {
          name: 'Big Bowser Blakely',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/13.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Big Bowser Blakely was a childhood friend of Duke Ellington. He appeared in "Duke".',
        },
        {
          name: 'Blue Jay',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/14.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'The Blue Jay is a bird that lives in a Nest outside of Bridgeton Middle School. Jay usually looks out the window and gets distracted by him, imagining what his life would be like if he were that bird. He appeared in "The ASSes".',
        },
        {
          name: 'Bob',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/15.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Bob is a hormone monster. He appeared in "The Department of Puberty".',
        },
        {
          name: 'Bobby Berk',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/16.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Bobby James Berk is the quaternary main character of Queer Eye. He appeared in the Big Mouth episode, "Disclosure the Movie: The Musical!".',
        },
        {
          name: 'Bootsy Collins',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/17.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'William "Bootsy" Earl Collins is a band member of Deee-Lite. He appeared in "The Planned Parenthood Show".',
        },
        {
          name: 'Brad',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/18.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'Brad is a couch pillow as well as Jays boyfriend.',
        },
        {
          name: 'Burt Reynolds',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/19.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Burt Leon Reynolds, Jr. was an American actor best known for his roles as Quint Asper in Gunsmoke, John Hawk from Hawk, Paul Crewe from The Longest Yard, and the titular character from Dan August. He appeared as a ghost in "My Furry Valentine", which aired a year after the death of his real-life counterpart.',
        },
        {
          name: 'Buster Keaton',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/20.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Joseph Frank Keaton (AKA Buster Keaton) was a famous comedian from the silent film era. He appeared in "Duke", where he was portrayed as a homosexual who was in love with his partner, Charlie Chaplin.',
        },
        {
          name: 'Caleb',
          age: '13',
          condition: 'Alive',
          image: 'http://localhost:3001/21.png',
          occupation: 'Student at Bridgeton High School',
          genre: 'Male',
          information: 'Caleb is a recurring character in Big Mouth. He is a student at Bridgeton Middle School, who participates in the school jazz club and works as the cameraman for the school news, which makes him part of the AV club. He is an asocial, yet very intelligent special needs kid who cant read social cues. He is a student at Bridgeton Middle School. He first appeared in "Everybody Bleeds". He is voiced by Joe Wengert.',
        },
        {
          name: 'Carlos Alvarez',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/22.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Carlos Alvarez is the brother of Gina Alvarez. He appeared in "The Shame Wizard".',
        },
        {
          name: 'Carol',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/23.png',
          occupation: 'Unknow',
          genre: 'Female',
          information: 'Carol was a womens physical fitness trainer at the gym, who used to work for Coach Steve. She was one of the victims of The Ponytail Killer. She never appeared in the show, but her picture was exhibited posthumously in "The Pornscape".',
        },
        {
          name: 'Cellsea',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/24.png',
          occupation: 'Phone',
          genre: 'Female',
          information: 'Cellsea is a cell phone that used to belong to Leah Birch, before she handed it down to Nick Birch who first appeared in "Cellsea".',
        },
        {
          name: 'Charles Lu',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/25.png',
          occupation: 'Student',
          genre: 'Male',
          information: 'Charles Lu is an attractive Asian guy who goes to Bridgeton Middle School. He is usually very quiet and doesnt say anything. He was a voiceless, nameless background character until he first spoke in "Rankings", when he rejected Jay, saying that he was straight. At Devin and Devons child wedding, he is seen dancing with Gina Alvarez.',
        },
        {
          name: 'Charlie Chaplin',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/26.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Sir Charles "Charlie" Spencer Chaplin was a famous comedian from the silent film era. He appeared in "Duke" as a homosexual who was in love with his partner, Buster Keaton.',
        },
        {
          name: 'Cheryl Glouberman',
          age: '13',
          condition: 'Alive',
          image: 'http://localhost:3001/27.jpg',
          occupation: 'Student',
          genre: 'Female',
          information: 'Cheryl Glouberman, better known as Cherry Maraschino, is Andrews cousin. Cherry is interested in Andrew as more than a cousin. She often flirts and teases him. Her character is voiced by Julie Klausner.',
        },
        {
          name: 'Choupette',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/28.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'Choupette is a Birman cat, famous for being the pet cat of Karl Lagerfeld. She appeared in "The Pornscape".',
        },
        {
          name: 'Church Girl',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/29.png',
          occupation: 'Unknow',
          genre: 'Female',
          information: 'The Church Girl was a girl that Duke Ellington was in love with. She appeared in "Duke".',
        },
        {
          name: 'Coach Steve',
          age: '47',
          condition: 'Alive',
          image: 'http://localhost:3001/30.png',
          occupation: 'Gym Coach Sex-Ed Teacher',
          genre: 'Male',
          information: 'Coach Steve is a major character in Big Mouth. He is the PE and sex-ed teacher at Bridgeton Middle School. He is very messed-up and characterized as a complete idiot, lacking knowledge in very basic everyday information. He is voiced by Nick Kroll.',
        },
        {
          name: 'Condom',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/31.png',
          occupation: 'Unknow',
          genre: 'Unknow',
          information: 'The Condom is a sheath-shaped barrier device used during sexual intercourse to reduce the probability of pregnancy or a sexually transmitted infection. It appeared as a personified character in "The Planned Parenthood Show".',
        },
        {
          name: 'Connie',
          age: '75,000,000',
          condition: 'alive',
          image: 'http://localhost:3001/32.png',
          occupation: 'Hormonal entity',
          genre: 'Female',
          information: 'Constance "Connie" Harland the Hormone Monstress (played by Maya Rudolph) is a monster that helps the FemaleFemale Symbol.png (with an exception being Nick Birch) characters during puberty. She usually shows up when a major event happens, like when Jessi Glaser gets her period or when Missy Foreman-Greenwald was kissing Andrew Glouberman. She seems to be the part of a females mind that yearns for glamour, saying things such as “Get rid!” like Jessi’s bra and baseball mitt. This was during S1E2 and S1E5.',
        },
        {
          name: 'Crumbum Tootles',
          age: 'Unknow',
          condition: 'Unknow',
          image: 'http://localhost:3001/33.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Crumbum Tootles is a childhood friend of Duke Ellington. He appeared in "Duke".',
        },
        {
          name: 'Cyrus Foreman-Greenwald',
          age: 'Unknow',
          condition: 'Alive',
          image: 'http://localhost:3001/34.png',
          occupation: 'Unknow',
          genre: 'Male',
          information: 'Cyrus Foreman-Greenwald is the father of Missy Foreman-Greenwald and the husband of Monica Foreman-Greenwald.',
        },
      ]));
};
